name: MagicStuff
version: '${project.version}'
main: fr.loanspac.magicstuff.MagicStuff
api-version: '1.21'
authors: [LoanSpac]
description: A Minecraft plugin to create custom item easily
commands:
  magic:
    description: "Give a Magic Sword"
    usage: "§cUsage /magic <give, list> <item, type>"
    aliases: [ms]
    permission: magic.common
    permission-message: "§cYou can't use this magic command, you should have [<permission>] permission"