name: MagicStuff
version: '${project.version}'
main: fr.loanspac.magicstuff.MagicStuff
api-version: '1.21'
authors: [LoanSpac]
description: A Minecraft plugin to create custom item easily
commands:
  magic:
    description: "Give a Magic Sword"
    usage: §cUsage /magic give <item>
    aliases: [ ms ]
    permission: magic.common
